server:
  port: 8988
  jsp-servlet:
    init-parameters:
      development: true

  context-path: /cmfz
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/chiming
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.baizhi.entity